name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: installRequirements
      run: pip install -r bin/requirements.txt

    - name: installHugo
      run: sudo snap install hugo
      
    - name: installbibutils
      run: |
        sudo apt-get update -y
        sudo apt-get install -y bibutils

    - name: Build
      run: sudo ANTHOLOGY_PREFIX="https://gwf-uwaterloo.github.io/gwf-publications" make

